/**
 * Sub2API 的 `reason` → 面向 UI 的稳定错误码。
 *
 * 映射表与 `codex/crates/codex-plus-core/src/lumio/errors.rs` 逐条对齐：同一个服务端 reason
 * 在桌面端与官网必须得到同一个码。服务端原文（message / 响应体）永不越过这一层。
 */

export type LumioErrorCode =
  | "AUTH_INVALID_CREDENTIALS"
  | "AUTH_ACCOUNT_DISABLED"
  | "AUTH_CODE_INVALID"
  | "AUTH_CODE_RATE_LIMITED"
  | "AUTH_CODE_REQUIRED"
  | "AUTH_REGISTRATION_CLOSED"
  | "AUTH_EMAIL_DOMAIN_NOT_ALLOWED"
  | "AUTH_EMAIL_ALREADY_REGISTERED"
  | "AUTH_EMAIL_INVALID"
  | "AUTH_INVITATION_CODE_REQUIRED"
  | "AUTH_INVITATION_CODE_INVALID"
  | "AUTH_2FA_INVALID"
  | "AUTH_2FA_UNAVAILABLE"
  | "AUTH_SESSION_EXPIRED"
  | "KEY_PROVISION_FAILED"
  | "AFFILIATE_QUOTA_EMPTY"
  | "SERVICE_RATE_LIMITED"
  | "SERVICE_UNAVAILABLE";

const REASON_MAP: Record<string, LumioErrorCode> = {
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  INVALID_USER: "AUTH_INVALID_CREDENTIALS",
  USER_NOT_ACTIVE: "AUTH_ACCOUNT_DISABLED",
  INVALID_VERIFY_CODE: "AUTH_CODE_INVALID",
  VERIFY_CODE_MAX_ATTEMPTS: "AUTH_CODE_INVALID",
  VERIFY_CODE_TOO_FREQUENT: "AUTH_CODE_RATE_LIMITED",
  EMAIL_VERIFY_REQUIRED: "AUTH_CODE_REQUIRED",
  VERIFY_CODE_REQUIRED: "AUTH_CODE_REQUIRED",
  REGISTRATION_DISABLED: "AUTH_REGISTRATION_CLOSED",
  EMAIL_SUFFIX_NOT_ALLOWED: "AUTH_EMAIL_DOMAIN_NOT_ALLOWED",
  EMAIL_RESERVED: "AUTH_EMAIL_DOMAIN_NOT_ALLOWED",
  EMAIL_EXISTS: "AUTH_EMAIL_ALREADY_REGISTERED",
  INVALID_EMAIL: "AUTH_EMAIL_INVALID",
  // 站点要求邀请码但用户没填 —— 可操作，绝不能伪装成服务故障让用户空转重试。
  INVITATION_CODE_REQUIRED: "AUTH_INVITATION_CODE_REQUIRED",
  // 填了但无效 / 已被使用；DISABLED 是邀请码功能整体关闭，用户填的码同样不会被接受，
  // 归到「无效」而非「需要填」，否则会催用户去填一个根本用不上的码。
  INVITATION_CODE_INVALID: "AUTH_INVITATION_CODE_INVALID",
  INVITATION_CODE_DISABLED: "AUTH_INVITATION_CODE_INVALID",
  TOTP_INVALID_CODE: "AUTH_2FA_INVALID",
  TOTP_TOO_MANY_ATTEMPTS: "AUTH_2FA_INVALID",
  TOTP_NOT_SETUP: "AUTH_2FA_UNAVAILABLE",
  TOTP_NOT_ENABLED: "AUTH_2FA_UNAVAILABLE",
  TOTP_SETUP_EXPIRED: "AUTH_2FA_UNAVAILABLE",
  TOTP_VERIFY_ERROR: "AUTH_2FA_UNAVAILABLE",
  EMAIL_VERIFY_NOT_ENABLED: "AUTH_2FA_UNAVAILABLE",
  INVALID_TOKEN: "AUTH_SESSION_EXPIRED",
  TOKEN_EXPIRED: "AUTH_SESSION_EXPIRED",
  ACCESS_TOKEN_EXPIRED: "AUTH_SESSION_EXPIRED",
  TOKEN_REVOKED: "AUTH_SESSION_EXPIRED",
  TOKEN_TOO_LARGE: "AUTH_SESSION_EXPIRED",
  REFRESH_TOKEN_INVALID: "AUTH_SESSION_EXPIRED",
  REFRESH_TOKEN_EXPIRED: "AUTH_SESSION_EXPIRED",
  REFRESH_TOKEN_REUSED: "AUTH_SESSION_EXPIRED",
  SESSION_BINDING_MISMATCH: "AUTH_SESSION_EXPIRED",
  GROUP_NOT_ALLOWED: "KEY_PROVISION_FAILED",
  API_KEY_EXISTS: "KEY_PROVISION_FAILED",
  API_KEY_RATE_LIMITED: "KEY_PROVISION_FAILED",
  API_KEY_TOO_SHORT: "KEY_PROVISION_FAILED",
  API_KEY_INVALID_CHARS: "KEY_PROVISION_FAILED",
  INVALID_IP_PATTERN: "KEY_PROVISION_FAILED",
  IDEMPOTENCY_KEY_REQUIRED: "KEY_PROVISION_FAILED",
  IDEMPOTENCY_KEY_CONFLICT: "KEY_PROVISION_FAILED",
  IDEMPOTENCY_IN_PROGRESS: "KEY_PROVISION_FAILED",
  IDEMPOTENCY_STORE_UNAVAILABLE: "KEY_PROVISION_FAILED",
  // affiliate 系列目前只有门户消费（桌面端无返利界面），不与 errors.rs 对表。
  AFFILIATE_QUOTA_EMPTY: "AFFILIATE_QUOTA_EMPTY",
};

const ERROR_TEXT: Record<LumioErrorCode, string> = {
  AUTH_INVALID_CREDENTIALS: "邮箱或密码不正确。",
  AUTH_ACCOUNT_DISABLED: "账号已被停用，请联系客服。",
  AUTH_CODE_INVALID: "验证码不正确或已失效，请重新获取。",
  AUTH_CODE_RATE_LIMITED: "验证码发送过于频繁，请稍后再试。",
  AUTH_CODE_REQUIRED: "请先获取邮箱验证码。",
  AUTH_REGISTRATION_CLOSED: "当前未开放注册。",
  AUTH_EMAIL_DOMAIN_NOT_ALLOWED: "该邮箱后缀不在允许注册的范围内。",
  AUTH_EMAIL_ALREADY_REGISTERED: "该邮箱已注册，请直接登录。",
  AUTH_EMAIL_INVALID: "请输入有效的邮箱地址。",
  AUTH_INVITATION_CODE_REQUIRED: "注册需要邀请码，请填写后重试。",
  AUTH_INVITATION_CODE_INVALID: "邀请码无效或已被使用。",
  AUTH_2FA_INVALID: "两步验证码不正确，请重新输入。",
  AUTH_2FA_UNAVAILABLE: "两步验证暂时不可用，请稍后再试。",
  AUTH_SESSION_EXPIRED: "登录已过期，请重新登录。",
  KEY_PROVISION_FAILED: "密钥开通失败，请稍后重试。",
  AFFILIATE_QUOTA_EMPTY: "暂无可划转的返利额度。",
  SERVICE_RATE_LIMITED: "请求过于频繁，请稍后再试。",
  SERVICE_UNAVAILABLE: "服务暂时不可用，请检查网络后重试。",
};

export function networkErrorCode(): LumioErrorCode {
  return "SERVICE_UNAVAILABLE";
}

export function normalizeReason(
  httpStatus: number,
  reason: string | null | undefined,
): LumioErrorCode {
  const key = reason?.trim();
  if (key && REASON_MAP[key]) return REASON_MAP[key];
  if (httpStatus === 429) return "SERVICE_RATE_LIMITED";
  if (httpStatus === 401) return "AUTH_SESSION_EXPIRED";
  return networkErrorCode();
}

export function errorText(code: LumioErrorCode): string {
  return ERROR_TEXT[code] ?? ERROR_TEXT.SERVICE_UNAVAILABLE;
}
