[package]
name = "test-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
fns-agent = { path = "../../bins/fns-agent" }
fns-platform = { path = "../../crates/fns-platform" }
fns-protocol = { path = "../../crates/fns-protocol" }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
